apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app
        image: muyleangin/fileupload:1.0
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: spring-volume
          mountPath: /images
      volumes:
      - name: spring-volume
        hostPath:
          path: /opt/spring/images
