apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-deploy
  template:
    metadata:
      labels:
        app: react-deploy
    spec:
      containers:
        - name: react-cont
          image: muyleangin/reactjs:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-svc
spec:
  type: NodePort
  selector:
    app: react-deploy
  ports:
  - name: nginx-app-port
    port: 80
    targetPort: 80
    nodePort: 30010
#testing push git 