- name: Run deploy with k8s
  hosts: workers
  become: true
  vars:
    repoURL: "https://gitlab.com/devops_gen_5/spring-argocd.git"
    # registry: "{{ registry }}"
    # imageName: "{{ imageName }}"
    # tag: "{{ tag }}"
    # fullImageName: "{{ registry }}/{{ imageName }}:{{ tag }}"
  tasks:
    - name: create directory 
      file:
        path: /root/deploy
        state: directory
        mode: 0755
    - name: copy k8s deployment file
      copy:
        src: "../shellscript/deploy-k8s-CD/argocdSpring.sh"
        dest: /root/deploy/argocdSpring.sh
    - name: Run script to deploy
      command: sh /root/deploy/argocdSpring.sh "{{ repoURL }}"