apiVersion: apps/v1
kind: Deployment
metadata:
  name: specialized-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: specialized-app
  template:
    metadata:
      labels:
        app: specialized-app
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  selector:
    app: nextjs-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30002
  type: NodePort