[workers]
node1 ansible_host=146.190.6.188 ansible_user=root ansible_ssh_private_key_file=~/.ssh/kube-key
node2 ansible_host=128.199.169.120 ansible_user=root ansible_ssh_private_key_file=~/.ssh/jenkin-key
