apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: argocd-clusterissuer
 namespace: argocd
spec:
 acme:
   server: https://acme-v02.api.letsencrypt.org/directory
   email: muyleanging@gmail.com
   privateKeySecretRef:
     name: argocd-clusterissuer
   solvers:
     - http01:
         ingress:
           class: nginx


